[tools]
pipx = "latest"
python = { version='3.14', virtualenv='.venv' }
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[env]
# Use the project name derived from the current directory
PROJECT_NAME = "{{ config_root | basename }}"
# Automatic virtualenv activation
_.python.venv = { path = ".venv", create = true }

PYTHONDONTWRITEBYTECODE = "1"
PYTHONUNBUFFERED = "1"
LC_ALL = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[tasks.tests]
description = "Run the test suite"
alias = "pytest"
run = [
  "uv run pytest tests/"
]

[tasks.format]
description = "Run the formatter"
alias = "f"
run = [
  "uv run ruff format ."
]
